services:
  - type: web
    name: hp-gas-cashmemo-tool
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
